server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://35.223.191.129:8761/eureka}
